header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - 'dist'
    - 'LICENSE.txt'
    - 'NOTICE.txt'
    - 'NOTICE'
    - '.gitignore'
    - '.github/PULL_REQUEST_TEMPLATE.md'
    - '.licenserc.yaml'
    - 'custom_env.sh.tpl'

  comment: on-failure
